### ISSUE TITLE
Latest example failed to run on K64F

### ISSUE THREAD

**Issue by jamesbeyond** [ARMmbed/mbed-os-example-mbed-crypto#29]
### Description

The latest example build successfullyon K64F, but failed to run.
Throw errors:
```
warning (-133) - this attempt at entropy injection failed
        assertion failed at .\main.cpp:375 - actual:-148expected:0
```
This was found by the new example smoke tests

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by k-stachowiak** [comment]
@jamesbeyond Thanks for raising this. Can you give more details about the failure conditions? In which branch was this observed? Was it `mbed-os-5.12`?

**Comment by k-stachowiak** [comment]
Never mind, I have reproduced it on `master`

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-785*

**Comment by jamesbeyond** [comment]
This issue might be same cause for attestation example
ARMmbed/mbed-os-example-attestation#13

**Comment by adbridge** [comment]
@k-stachowiak any news on this? OOB starts tomorrow and it would be nice to have both this and the attestation bugs fixed beforehand ?

**Comment by k-stachowiak** [comment]
@adbridge I am working on it right now. We have established that there is an issue regarding gathering entropy from the device, however the root cause has not yet been found. It is difficult to predict, if I can make it today, but there are no clear signs of this being a big issue yet.

**Comment by adbridge** [comment]
@k-stachowiak is it the same issue on both examples ?

**Comment by k-stachowiak** [comment]
It most likely is. It's the same function (`psa_crypto_init()`) failing with the same error code.

**Comment by k-stachowiak** [comment]
@adbridge The root cause has been found and a PR raised here: https://github.com/ARMmbed/mbed-crypto/pull/138
Unfortunately, we didn't find a way of fixing it cleanly on the examples' side, so the fix must be made to the Mbed Crypto feature.

**Comment by 0xc0170** [comment]
How to get  this fix to MBed OS? Does this mean crypto will be updated for 5.13 release candidate?

**Comment by k-stachowiak** [comment]
It would probably be best for @Patater to comment on that, but it looks to me like that may be necessary the way we're fixing it now.

**Comment by adbridge** [comment]
@k-stachowiak so that would effectively mean a new TLS/Crypto release to Mbed OS ? How long is that likely to take ?

**Comment by Patater** [comment]
@adbridge PR to Mbed OS will be up by the end of the day today.

**Comment by evedon** [comment]
I ran mbed-os-example-mbed-crypto on K64F using GCC_ARM with mbed-os-5.13.0-rc3 and I still get a warning. No assert though.
```
warning (-133) - this attempt at entropy injection failed
cipher encrypt/decrypt AES CBC no padding:
        success!
cipher encrypt/decrypt AES CBC PKCS7 multipart:
        success!
cipher encrypt/decrypt AES CTR multipart:
        success!
```
@Patater is that expected? If so, we should probably document it somewhere.

**Comment by Patater** [comment]
@evedon Yes, the warning is OK. You'll get it if you already have entropy injected, which happens if you run twice with the same SD card installed (and the SD card is used for KvStore). I'll add this to the README

**Comment by evedon** [comment]
I don't have a SD card though.

**Comment by Patater** [comment]
K64F can use internal flash for KvStore as well, and if anyone ever has injected entropy at least once, your K64F will always display this until KvStore is erased.
