### ISSUE TITLE
[5.14 OOB] K64F target fails to run getting started.

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/mbed-os-example-mbed-crypto#45]
### Description

Target: K64F
Toolchain: GCC_ARM
branch: mbed-os-5.14

terminal output:
```
Not all of the requirements are met:
  - MBEDTLS_PSA_CRYPTO_C
  - PSA Crypto API v1.0b3
```

### Issue request type

    [ ] Question
    [ ] Enhancement
    [ x] Bug

**Comment by adbridge** [comment]
@Patater Could you please help Ben ?

**Comment by Patater** [comment]
rc1 doesn't have PSA Crypto API 1.0b3 for this example. Try with rc2 please.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-895*

**Comment by Patater** [comment]
Closing as fixed. Example runs OK in CI.
