### ISSUE TITLE
Doesn't work on platforms with hardware-accelerated cryptography

### ISSUE THREAD

**Issue by manchoz** [ARMmbed/mbed-os-example-mbed-crypto#50]
### Description

Calls to crypto functions get stuck on platforms with support for hardware-accelerated cryptography.

Tested on nRF52840 boards.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-987*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2110*
