### ISSUE TITLE
Following instructions in README doesn't deploy Mbed OS correctly

### ISSUE THREAD

**Issue by rajkan01** [ARMmbed/mbed-os-example-mbed-crypto#61]
### Description

Following instructions on https://github.com/ARMmbed/mbed-os-example-mbed-crypto/commit/8d5d8aba5583f9d0dce8e9b5cce493d1051ca09c doesn't result in working software.

After cloning and then following - https://github.com/ARMmbed/mbed-os-example-mbed-crypto#import , the `mbed compile -m K64F -t ARM fails.

Followed the below procedure and successfully able to build and run the example in K64F target

1.  git clone https://github.com/ARMmbed/mbed-os-example-mbed-crypto
2. cd mbed-os-example-mbed-crypto/getting-started
3. mbed deploy
4. mbed compile -m K64F -t ARM

### Issue request type

[ ] Question  
[ ] Enhancement  
[ x] Bug

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-1064*
